language: go

sudo: required
language: go

go:
- "1.11.x"

install:
  - export GO111MODULE=on
  - go get github.com/golang/mock/gomock
  - go install github.com/golang/mock/mockgen

script: make generate test
